spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: dingdingcrong
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: trace